migrate(
  (app) => {
    const vehicles = app.findCollectionByNameOrId('vehicles')
    vehicles.fields.add(new NumberField({ name: 'purchase_value' }))
    vehicles.fields.add(new NumberField({ name: 'resale_value' }))
    vehicles.fields.add(new TextField({ name: 'brand_model' }))
    vehicles.fields.add(new NumberField({ name: 'year' }))
    vehicles.fields.add(new TextField({ name: 'vehicle_type' }))
    vehicles.fields.add(new NumberField({ name: 'consumption' }))
    vehicles.fields.add(new NumberField({ name: 'diesel_price' }))
    vehicles.fields.add(new NumberField({ name: 'ipva' }))
    vehicles.fields.add(new NumberField({ name: 'licensing' }))
    vehicles.fields.add(new NumberField({ name: 'insurance' }))
    vehicles.fields.add(new NumberField({ name: 'tire_cost' }))
    vehicles.fields.add(new NumberField({ name: 'maintenance' }))
    vehicles.fields.add(new NumberField({ name: 'cleaning' }))
    vehicles.fields.add(new BoolField({ name: 'arla_32' }))
    app.save(vehicles)

    const vinculos = app.findCollectionByNameOrId('vinculos')
    vinculos.fields.add(new NumberField({ name: 'estimated_km' }))
    app.save(vinculos)

    const settings = app.findCollectionByNameOrId('fleet_settings')
    settings.fields.add(new JSONField({ name: 'hq_costs' }))
    settings.fields.add(new JSONField({ name: 'taxes_config' }))
    app.save(settings)
  },
  (app) => {
    const vehicles = app.findCollectionByNameOrId('vehicles')
    vehicles.fields.removeByName('purchase_value')
    vehicles.fields.removeByName('resale_value')
    vehicles.fields.removeByName('brand_model')
    vehicles.fields.removeByName('year')
    vehicles.fields.removeByName('vehicle_type')
    vehicles.fields.removeByName('consumption')
    vehicles.fields.removeByName('diesel_price')
    vehicles.fields.removeByName('ipva')
    vehicles.fields.removeByName('licensing')
    vehicles.fields.removeByName('insurance')
    vehicles.fields.removeByName('tire_cost')
    vehicles.fields.removeByName('maintenance')
    vehicles.fields.removeByName('cleaning')
    vehicles.fields.removeByName('arla_32')
    app.save(vehicles)

    const vinculos = app.findCollectionByNameOrId('vinculos')
    vinculos.fields.removeByName('estimated_km')
    app.save(vinculos)

    const settings = app.findCollectionByNameOrId('fleet_settings')
    settings.fields.removeByName('hq_costs')
    settings.fields.removeByName('taxes_config')
    app.save(settings)
  },
)
